apiVersion: v1
kind: Pod
metadata:
  name: my-shell
spec:
  containers:
    - name: main
      image: nginx
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /airflow/dags
          name: dags
  volumes:
    - name: dags
      persistentVolumeClaim:
        claimName: dags-claim